### ISSUE TITLE
EvangelistStatus.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-ooduye/EvangelistStatus#1]

**Comment by unicodeveloper** [comment]
There should be space between line 10 and 11

**Comment by unicodeveloper** [comment]
All the functions in this class should be commented

**Comment by unicodeveloper** [comment]
The function name should be `getUsernameAndCompany()` and on line 61, it's better to throw an exception stating the username can't be found.

**Comment by unicodeveloper** [comment]
In function getStatus(), line 100, you shouldn't echo there, just return a string.

**Comment by ooduye** [comment]
It is not the username that is being gotten but the user's name and company.

**Comment by unicodeveloper** [comment]
Ohh...then it should be something like `getNameAndCompany` , the way it was, I taught it was username
