### ISSUE TITLE
UserData.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-ooduye/EvangelistStatus#4]
The `client_id` and `client_secret` should have their own variables to enable easy change. Someone might mess up with the query string when trying to change those values the way it is currently been implemented.

The `client_id` and `client_secret` values should also not be stored in the code, it's more appropriate to use environment variables. Right now the whole world can see your `client_id` and `client_secret` values but if you use a `.env` file, you'll be safe from that

**Comment by unicodeveloper** [comment]
There should be space between line 9 and line 10

**Comment by unicodeveloper** [comment]
On line 20, I know it is public by default, Please still endeavour to put the `public` to make it more semantic.

**Comment by unicodeveloper** [comment]
`if(isset($decoded_result->id)) {
            return $decoded_result;
        } else {
            throw new InvalidUsernameException($decoded_result->message);
        }`

$decoded_result->message - does it have a message that states that the username doesn't exist?

**Comment by ooduye** [comment]
Yes the `$decoded_result->message` contains a string "Not Found" and I built on it in the `InvalidUsernameException` for it to return `Error! Username Not Found`

**Comment by unicodeveloper** [comment]
Cool
