### ISSUE TITLE
EvangelistStatusExceptionTest.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-ooduye/EvangelistStatus#5]
`testInvalidUsernameException()` should have been something like so

$expected = "";
try {
            // ... Code that is expected to raise an exception ...
            UserData::makeApiCall("andela-vdugri");
        }
        catch (InvalidUsernameException $e) {
            $expected = $e->getErrorMessage();
        }
$this->assertEquals("Invalid Username", $expected);

**Comment by ooduye** [comment]
I was going through the PHPUnit and that test is to test if an exception is thrown as should be. The `testInvalidUsernameExceptionMessage()` is the one that now checks for the assertsEqual to check if the right message is what was thrown and if no exception is thrown it returns the string within the `$this->fail`

**Comment by unicodeveloper** [comment]
Awesome Explanation..that's good :+1:
